In [31]:
import numpy as np
import pickle
import warnings
warnings.filterwarnings('ignore')

In [32]:
ohe_sex = pickle.load(open('C:/Users/gupta/OneDrive/Documents/Machine Learning/14_Pipelines/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('C:/Users/gupta/OneDrive/Documents/Machine Learning/14_Pipelines/ohe_embarked.pkl','rb'))
clf = pickle.load(open('C:/Users/gupta/OneDrive/Documents/Machine Learning/14_Pipelines/clf.pkl','rb'))

In [ ]:
# Sample User Input 
# PClass/Gender/Age/SibSp/Parch/Fare/Embarked
test_input = np.array([2,'male',31.0, 0, 0, 10.5,'S'],dtype=object).reshape(1,7)

In [34]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

### Applying Transformations :

In [35]:
test_input_sex = ohe_sex.transform((test_input[:,1]).reshape(1,1))
test_input_sex

array([[0., 1.]])

In [36]:
test_input_embarked = ohe_embarked.transform((test_input[:,-1]).reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [37]:
# Extracting 'age' column
test_input_age = test_input[:,2].reshape(1,1)
test_input_age

array([[31.0]], dtype=object)

In [38]:
# Joining
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]] , 
                                        test_input_age ,test_input_sex ,
                                        test_input_embarked),axis=1)


In [39]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

### Without using Pipeline :

In [40]:
ans = clf.predict(test_input_transformed)

if (ans == 1):
    print("Survived✅")
else:
    print("Not Survived❌")

Survived✅
